Implemented Password Pawned Checker
codezoned/PsipherBackend pull request #31
Opened 2020-08-27 17:18 UTC by naveennivas

**Classes Created** 
1. PasswordPawnedOperationsImpl  --> _under actions_ (with the interface PasswordPawnedOperations)
          -> Implemented the method _pawned checker_ from the interface.
          -> The method makes use of the pawned checker api from github to check whether the password has been pawned or not.
          -> Returns true(leaked) or false (not leaked) to the object passwordpawnedoutput in the class _PasswordPawnedOutput_
          -> The status variable in the output method is also set here.

2. PasswordPawnedChecker -->  _under api_
           -> Input parameter password is received to string _pass_ then this is passed to the method on to _PasswordPawnedOperationsImpl_ to check whether its leaked or not.

3. PasswordPawnedOutput --> _under model_
            -> has a method called _PasswordPawnedOutput_ which contains a boolean _status_ variable to say true(leaked) or false(not leaked/safe).
 **Edits made in _POM.xml_**
1. added dependencies  from _https://www.twilio.com/blog/2018/06/round-up-libraries-for-checking-pwned-passwords-in-your-7-favorite-languages.html_ 
2. added dependencies  from _https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp_

2020-08-27 21:46 UTC, rahulkrishnan221 requested changes

2020-08-27 21:46 UTC, rahulkrishnan221 commented on src/main/java/com/psipher/application/api/PasswordPawnedChecker.java
> +    @RequestMapping(path = "/passwordpawnedchecker", method = RequestMethod.GET)
It should not be a get request

2020-08-27 21:46 UTC, rahulkrishnan221 commented on src/main/java/com/psipher/application/actions/PasswordPawnedOperationsImpl.java
> +    public PasswordPawnedOutput passwordpawnedchecker(String pass) {
We should not reuse the model which was used in rest output request. For internal model create a new model or just pass a boolean. We dont need extra model here

2020-08-27 21:46 UTC, rahulkrishnan221 commented on src/main/java/com/psipher/application/actions/PasswordPawnedOperationsImpl.java
> +        PwnedPasswordClient client = new PwnedPasswordClient(new OkHttpClient(), "https://api.pwnedpasswords.com/range", "");
Move this url https://api.pwnedpasswords.com/range to resource or config and url and extract from that place

2020-08-27 21:46 UTC, rahulkrishnan221 commented on src/main/java/com/psipher/application/actions/PasswordPawnedOperationsImpl.java
> +    public PasswordPawnedOutput passwordpawnedchecker(String pass) {
NIT: change from passwordpawnedchecker --> passwordPawnedChecker

2020-08-27 21:46 UTC, rahulkrishnan221 commented on src/main/java/com/psipher/application/actions/PasswordPawnedOperations.java
> +    PasswordPawnedOutput passwordpawnedchecker(String pass);
Change output to boolean why do we need to depend on rest output object

2020-08-27 21:46 UTC, rahulkrishnan221 commented on src/main/java/com/psipher/application/actions/PasswordPawnedOperations.java
> +     * @return pawned or not
NIT: @return true/false

2020-08-27 21:46 UTC, rahulkrishnan221 commented on src/main/java/com/psipher/application/api/PasswordPawnedChecker.java
> +    PasswordPawnedOperations passwordpawnedoperations;
make this private

2020-08-28 04:37 UTC, naveennivas commented
Have made the changes requested.

2020-08-28 20:33 UTC, rahulkrishnan221 approved these changes

2020-08-28 20:34 UTC, merged